fix: error messages for international shipment
postnl/woocommerce pull request #73
Opened 2021-01-14 14:10 UTC by RichardPerdaan

It is also possible to send letters for an international shipment and a label description is not required, but an invoice is required.

2021-01-14 14:14 UTC, EdieLemoine requested changes

2021-01-14 14:14 UTC, EdieLemoine commented on includes/admin/OrderSettingsRows.php
> +                "options"           => $packageType,
De naam van de variabele is best wel onduidelijk, doe dan `$packageTypeOptions`

2021-01-14 14:14 UTC, EdieLemoine commented on readme.txt
> +Tags: woocommerce, export, delivery, packages, Postnl, postnl
die dubbele postnl kan weg, het is niet hoofdlettergevoelig

2021-01-14 16:00 UTC, EdieLemoine approved these changes

2021-01-14 16:00 UTC, EdieLemoine commented on includes/admin/OrderSettingsRows.php
> +        $orderSettings = new OrderSettings($deliveryOptions, $order);
uitlijning :/

2021-01-15 08:10 UTC, robindelaater approved these changes

2021-01-15 08:53 UTC, merged