feat: add option to disable insurance for shipments to Belgium
postnl/woocommerce pull request #81
Opened 2021-12-20 08:12 UTC by markernst97

It is not possible to open a pull request. Make a fork to keep your own version.

2021-12-21 08:37 UTC, EdieLemoine requested changes

2021-12-21 08:37 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +    public const DEFAULT_BELGIAN_INSURANCE = 500;
uitlijnen

2021-12-21 08:37 UTC, EdieLemoine commented on includes/admin/OrderSettings.php
> +            $isInsured = $isDefaultInsuredForBE;
uitlijnen

2021-12-21 08:37 UTC, EdieLemoine commented on includes/admin/OrderSettingsRows.php
> +            $rows[] = [
single quotes

2021-12-21 08:37 UTC, EdieLemoine commented on includes/admin/settings/class-wcpost-settings.php
> +    public const SETTING_CARRIER_DEFAULT_EXPORT_INSURED_FOR_BE           = 'export_insured_for_be';
uitlijnen

2021-12-21 08:51 UTC, joerivanveen approved these changes

2021-12-29 10:49 UTC, RichardPerdaan approved these changes

2021-12-29 10:53 UTC, merged