fix: change post data sanitization for shipping method
postnl/woocommerce pull request #87
Opened 2022-11-02 15:26 UTC by Mark-Ernst

2022-11-03 12:22 UTC, joerivanveen requested changes

2022-11-03 12:22 UTC, joerivanveen commented on includes/frontend/class-wcpn-checkout.php
> +        $shippingMethod = wp_filter_post_kses($_POST['shipping_method'][0]);
Zoals besproken via slack, probeer $_POST te vermijden als het kan

2022-11-08 08:49 UTC, joerivanveen approved these changes

2022-11-08 09:03 UTC, wthijmen approved these changes

2022-11-09 13:02 UTC, merged